# Knowledge Management System Configuration

# Document indexing settings
indexing:
  # Directories to scan for documents
  target_directories:
    # - "~/Documents"
    - "~/Downloads"

  # Supported file types
  file_extensions:
    - ".txt"
    - ".md"
    - ".pdf"

  # ChromaDB storage location
  storage_path: "./chroma_db"

  # Document chunk settings
  chunk_size: 1024
  chunk_overlap: 200

  # PDF-specific settings
  pdf:
    enabled: true
    max_file_size_mb: 100  # Skip PDFs larger than this
    extract_metadata: true  # Include page numbers and file metadata
    skip_encrypted: true    # Skip password-protected PDFs
    timeout_seconds: 60     # Per-file processing timeout

# OpenAI configuration
openai:
  # API key (set via environment variable OPENAI_API_KEY)
  model: "gpt-3.5-turbo"
  embedding_model: "text-embedding-ada-002"
  temperature: 0.7
  max_tokens: 1000

# UI preferences
ui:
  window_width: 800
  window_height: 600
  theme: "system" # system, light, dark
  font_size: 12

# System settings
system:
  log_level: "INFO"
  max_results: 10
  enable_debug: true

# Long-running operations settings
operations:
  # SQLite database for tracking operations
  database_file: "tmp/operations.db"

  # How long to keep completed operations (hours)
  cleanup_after_hours: 24

  # Maximum time allowed for any operation (seconds)
  max_timeout_seconds: 3600

# Team-based knowledge system settings
team:
  # Enable team-based architecture (vs single agent)
  enabled: true

  # Team memory settings
  memory:
    enabled: true
    database_file: "tmp/team_memory.db"

  # Agent specialization settings
  agents:
    planning:
      temperature: 0.3 # Lower for focused planning
      role: "Query Analysis and Team Orchestration"

    metadata:
      temperature: 0.2 # Very focused for metadata extraction
      role: "Metadata Extraction and Query Optimization"

    search:
      temperature: 0.4 # Balanced for search execution
      role: "Knowledge Base Search Execution"

    assembly:
      temperature: 0.6 # Higher creativity for synthesis
      role: "Result Synthesis and Response Assembly"

  # Collaboration settings
  collaboration:
    show_member_responses: false # Keep responses clean
    enable_agentic_filters: true
    max_search_iterations: 3
