# Knowledge Management System Configuration

# Document indexing settings
indexing:
  # Directories to scan for documents
  target_directories:
    - "~/Documents"
    - "~/Downloads"
  
  # Supported file types
  file_extensions:
    - ".txt"
    - ".md"
    - ".pdf"
  
  # ChromaDB storage location
  storage_path: "./chroma_db"
  
  # Document chunk settings
  chunk_size: 1024
  chunk_overlap: 200

# OpenAI configuration
openai:
  # API key (set via environment variable OPENAI_API_KEY)
  model: "gpt-3.5-turbo"
  embedding_model: "text-embedding-ada-002"
  temperature: 0.7
  max_tokens: 1000

# UI preferences
ui:
  window_width: 800
  window_height: 600
  theme: "system"  # system, light, dark
  font_size: 12

# System settings
system:
  log_level: "INFO"
  max_results: 10
  enable_debug: false